### ISSUE TITLE
🛑 ERROR >> Invalid token or no bots are available.

### ISSUE THREAD

**Issue by Dmitrium12** [AvenCores/free-chatpt4.0-cli#1]
apparently everything has already been covered up

**Comment by AvenCores** [comment]
новая версия в разработке

**Comment by Dmitrium12** [comment]
это очень круто, жду не дождусь)

**Comment by AvenCores** [comment]
> это очень круто, жду не дождусь)

https://github.com/AvenCores/free-chatpt4.0-cli/releases/tag/V1.0.2
