### ISSUE TITLE
версия не 4, а 3.5-турбо

### ISSUE THREAD

**Issue by Dmitrium12** [AvenCores/free-chatpt4.0-cli#2]
![image](https://user-images.githubusercontent.com/57551797/235339312-ca5ab285-36a7-4184-8ef8-940769e56cd8.png)
![image](https://user-images.githubusercontent.com/57551797/235339330-f53ad0a1-4886-45d5-8425-f53085d232a0.png)

**Comment by AvenCores** [comment]
На данный момент нету рабочего фри апи для gpt4
Отпиши мне в тг `@avencores` или жди сюда когда скину обнову

**Comment by exportnsk54** [comment]
чет не работает нефига
![12312](https://github.com/AvenCores/free-chatpt4.0-cli/assets/135452102/a04bacde-1b73-42e1-a250-6067c0a501b6)
